public enum MessageType
{
    SCENE_CHANGE_LOGIN_TO_WORLD,
    CONNECT_TO_WORLD,
    UPDATE_USER_BASEINFO,
    UPDATE_USER_EXP,
    UPDATE_USER_LEVEL,
    UPDATE_USER_HP,
    UPDATE_USER_POSITION,
    ATTACK_NPC,
    CREATE_NPC,
}