public enum MessageType
{
    SCENE_CHANGE_LOGIN_TO_WORLD,
    CONNECT_TO_WORLD,
    UPDATE_USER_BASEINFO,
    UPDATE_USER_EXP,
    UPDATE_USER_LEVEL,
    UPDATE_USER_HP,
    UPDATE_USER_POSITION,
    UPDATE_NPC_POSITION,
    ATTACK_NPC,
    CREATE_NPC,
    CREATE_PLAYER,
    REMOVE_OBJECT,
    DAMAGED_NPC,
    PLAYER_DAMAGED,
    CHATTING,
}